config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self) 



      get '/post', to: 'posts#post'
      get '/marketing', to: 'posts#marketing'
      get '/posts/:id', to: 'posts#show', as: 'show_post'

    resources :enquiries      

  root "posts#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable


  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "id_value", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/enquiry.rb
class Enquiry < ApplicationRecord

    def self.ransackable_attributes(auth_object = nil)
        ["created_at", "description", "email", "id", "id_value", "name", "subject", "updated_at"]
      end
end

app/models/post.rb
class Post < ApplicationRecord
    has_one_attached :image


  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "description", "id", "id_value", "title", "updated_at"]
  end
  def self.ransackable_associations(auth_object = nil)
    ["image_attachment", "image_blob"]
  end


  enum type: { designing: 0, development: 1, mobile: 2 }

  attribute :type
  self.inheritance_column = :post_type

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/enquiries_controller.rb
class EnquiriesController < ApplicationController
    def new
        @enquiry = Enquiry.new
    end

    def create
        @enquiry = Enquiry.new(enquiry_params)
        if @enquiry.save
            redirect_to root_path
    end
end
    private

    def enquiry_params
        params.require(:enquiry).permit(:name, :subject, :email, :description)        
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def index

    end

    def post
        @posts = Post.where(type: params[:type]) 
    end

    def marketing

    end


    def show
      @post = Post.find(params[:id])
    end
    
   

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/enquiries/new.html.erb
<div class="b-container">
        <h2 class="cont-h">Contact Us.</h2>
        <div class="cont-form">
            <%= form_with model: @enquiry do |form|%>
                    <%= form.text_field :name, placeholder: "Your Name Here", class:"cont-input-1"%>
                
                    <%= form.text_field :subject, placeholder: "Subject", class: "cont-input" %><br/>

                    <%= form.email_field :email, placeholder: "example@gamil.com", class: "cont-input-2"  %>

                    <%= form.text_area :description, placeholder:"Type What You Want To Say.", class: "cont-text" %>
                    
                    <%= form.submit "Submit", class: "cont-btn"%>
            <% end %>
        </div>
      <div class="cont-copy">
         <p class="cont-copy-p">© CodeeFly 2023 | All Rights Reserved</p>
         </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Agency</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
    <link href=" https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/css/splide.min.css " rel="stylesheet">


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
  <%= render partial: "shared/navbar"%>
  <%= turbo_frame_tag "modal", target: "_top" %>
    <%= yield %>
  </body>
</html>

app/views/main/contact.html.erb
<div class="c-container">
    <div class="cont-form">
        <h2 class="cont-h">Contact Us.</h2>

        <form>
            <input type="text" placeholder="Your Name Here" class="cont-input-1">
            <input type="text" placeholder="Subject" class="cont-input"><br/>
            <input type="email" placeholder="example@gamil.com" class="cont-input-2">
            <textarea placeholder="Type What You Want To Say." class="cont-text"></textarea>
            <button class="cont-btn">Submit</button>
        </form>
    <div class="cont-copy">
        <p class="cont-copy-p">© CodeeFly 2023 | All Rights Reserved</p>
    </div>  
</div>

app/views/main/index.html.erb
<div class="b-container">
    <div>
    <div class="p-text">
        <p class="p-style">Professionals focused on helpingyour<br/>brand grow and move forward</p>
    </div>
    <div class="text-t">
        <h1 class="h-style">Designing a Better World <span class="span-s">Today</span></h1>
    </div>
    <div class="p-to-p">
        <p class="p-p">
        I'm a passionate UI/UX designer with a
         mission to create delightful and intuitive digital experiences.
         With a strong foundation in design principles and a keen eye for
         detail, I specialize in translating complex ideas into
         user-friendly interfaces that captivate and engage.
         </p>
    </div>
    <button class="btn-1">Get Started</button>
    <div>
    <div>
    <%= image_tag src="/assets/Screenshot from 2024-02-28 15-27-10.png", class: "img-size-2" %>
    </div>
</div>

app/views/main/marketing.html.erb
<div class="c-container">
    <div class="box">
        <div class="pro-pp">
            <p class="pro-p">CONTENT MARKETING</p>
        </div>
        <div class="pro-text">
            <h2 class="pro-h">Weaving Magic into  <br/> Your Business</h2>
        </div><br/>
        <div class="market-box">
            <div class="info-box">
                <h6 class="mark-h">Creative Agency</h6>
                <hr class="b-r">
                <h5 class="mark-h-6">Framer Designer & Developer</h5>
                <p class="mark-p">2019 - present</p>
                <p class="mark-p-2">
                    Nemo enim ipsam voluptatem quia voluptas
                    sit aspernatur autodit aut fugit sed<br/>  thisnquia 
                    consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt    
                 </p>
                 <p class="read-m">Read more</p>
                 <div class="hr-1">
                    <div class="hr-2">
                    </div>
                 </div>
            </div>

            <div class="info-box">
                <h6 class="mark-h">Creative Agency</h6>
                <hr class="b-r">
                <h5 class="mark-h-6">Framer Designer & Developer</h5>
                <p class="mark-p">2019 - present</p>
                <p class="mark-p-2">
                    Nemo enim ipsam voluptatem quia voluptas
                    sit aspernatur autodit aut fugit sed<br/>  thisnquia 
                    consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt    
                </p>
                <p class="read-m">Read more</p>
                <div class="hr-1">
                    <div class="hr-2">
                    </div>
                </div>
            </div>
        </div>
        
</div>

app/views/main/project.html.erb
<div class="c-container">
    <div class="box">
        <div class="pro-pp">
            <p class="pro-p">CREATIVE DESIGNING</p>
        </div>
        <div class="pro-text">
            <h2 class="pro-h">Our Creative for the Creative World</h2>
        </div><br/>
        <div class="box-1">
            <div class="project">
                <%= image_tag src="/assets/8a4e21e54eb7c3255fa6793c21f9f2d4.jpeg", class: "project-img"%><br/>
                <p class="pro-p">Where Passion and Purpose Collide</p>
                <p class="pro-p1">Lorem Ipsum is simply dummy text of the printing     
                and types etting in our company here thisn designers give me more design here
                </p>
            </div>
            <div class="project">
                <%= image_tag src="/assets/88e48f002e981eb4dd4534bfef889696.jpeg", class: "project-img"%><br/>
                <p class="pro-p">Where Passion and Purpose Collide</p>
                <p class="pro-p1">Lorem Ipsum is simply dummy text of the printing     
                and types etting in our company here thisn designers give me more design here
                </p>
            </div>
            <div class="project">
                <%= image_tag src="/assets/f1647f3d6960262cb8c598d1da55c518.jpeg", class: "project-img"%></br>
                <p class="pro-p">Where Passion and Purpose Collide</p>
                <p class="pro-p1">Lorem Ipsum is simply dummy text of the printing     
                and types etting in our company here thisn designers give me more design here
                </p>
            </div>
        </div>
    </div>
</div>

app/views/posts/index.html.erb
<div class="b-container">
    <div class="margin">
        <p class="p-style">Professionals focused on helpingyour<br/>brand grow and move forward</p>
        <h1 class="h-style">Designing a Better World <span class="span-s">Today</span></h1>
    <div class="p-to-p">
        <p>
        I'm a passionate UI/UX designer with a
         mission to create delightful and intuitive digital experiences.
         With a strong foundation in design principles and a keen eye for
         detail, I specialize in translating complex ideas into
         user-friendly interfaces that captivate and engage.
         </p>
    </div>
    <button class="btn-1">Get Started</button>
    </div>
</div>

app/views/posts/marketing.html.erb
<div class="b-container">
    <div class="box">
            <p class="pro-p">CONTENT MARKETING</p>
            <h2 class="pro-h">Weaving Magic into  <br/> Your Business</h2>
        </div><br/>
        <div class="market-box">
            <div class="info-box">
                <h6 class="mark-h">Creative Agency</h6>
                <hr class="b-r">
                <h5 class="mark-h-6">Framer Designer & Developer</h5>
                <p class="mark-p">2019 - present</p>
                <p class="mark-p-2">
                    Nemo enim ipsam voluptatem quia voluptas
                    sit aspernatur autodit aut fugit sed thisnquia 
                    consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt    
                 </p>
                 <p class="read-m">Read more</p>
                 <div class="hr-1">
                    <div class="hr-2">
                    </div>
                 </div>
            </div>

            <div class="info-box">
                <h6 class="mark-h">Creative Agency</h6>
                <hr class="b-r">
                <h5 class="mark-h-6">Framer Designer & Developer</h5>
                <p class="mark-p">2019 - present</p>
                <p class="mark-p-2">
                    Nemo enim ipsam voluptatem quia voluptas
                    sit aspernatur autodit aut fugit sed  thisnquia 
                    consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt    
                </p>
                <p class="read-m">Read more</p>
                <div class="hr-1">
                    <div class="hr-2">
                    </div>
                </div>
            </div>
        </div>
        
</div>

app/views/posts/post.html.erb
<div class="b-container">
  <% if request.original_fullpath == '/post?type=designing'%>
    <div class="box">      
        <h1 class="pro-p">CREATIVE DESIGNING</h1>
        <h2 class="pro-h">Our Creative for the Creative World</h2>
    </div>

  <% elsif request.original_fullpath == '/post?type=development'%>  
    <div class="box">      
        <h1 class="pro-p">WEB DEVELOPMENT</h1>
        <h2 class="pro-h">Actionable Insights Real-World Experience</h2>
    </div>

  <% elsif request.original_fullpath == '/post?type=mobile'%>  
    <div class="box">      
        <h1 class="pro-p">MOBILE DEVELOPMENT</h1>
        <h2 class="pro-h">Transforming Ideas Into Digital Experiences</h2>
    </div>
  <% end %>

        <div class="box-1">
        <% @posts.each do |post| %>
                <div class="project">
                    <% if post.image.attached? %>
                        <%= image_tag url_for(post.image), class: "project-img"%>
                    <% end %>    <br/>
                    <p class="pro-p-2"><%= post.title %></p>
                    <p class="pro-p1">
                      <% description_words = post.description.split(' ') %>
                      <% truncated_description = description_words.take(20).join(' ') %>
                      <%= truncated_description %>...<%=  link_to "Read more",  show_post_path(post), data: {turbo_frame: 'modal'}, class:"color-r"%>
                </div>
                <% end %>
        </div>
    </div>
    
    

    
</div>

app/views/posts/show.html.erb
<%= turbo_frame_tag "modal" do %>
    <div class="modal fade " tabindex="-1" data-controller="modal">
      <div class="modal-dialog modal-dialog-centered modal-lg ">
        <div class="modal-content ">
          <div class="modal-container">
            <button type="button" class="btn-close btn-close-white close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body modal-container" id="remote_modal_body" >
            <%= yield %>
            <%= render 'shared/modal'%>
          </div>
        </div>
      </div>
    </div>
  <% end %>

app/views/shared/_modal.html.erb
<div class="modal-box">
    <div class="modal-img">
      <%= image_tag (@post.image), class: "modal-img" %>
    </div>
    <div class="modal-text">
      <h1 class="modal-h1"><%= @post.title %></h1>
      <p class="modal-p"><%= @post.description%></p>
    </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="sidebar-container">
        <div class="logo">
            <div class="log">
                <h1>S.</h1>    
            </div>
            <div class="nav-1">
                <ul>
                  <a href="/" class="A-t">
                    <li class="ill-1">
                      <span class="color-b <%= 'color-v' if request.original_fullpath == '/'%>"><i class="bi bi-house-door-fill "></i></span>
                      <span class="lli-1 <%= 'color-r' if request.original_fullpath == '/'%>">HOME</span>
                    </li>
                  </a>
                <a href="/post?type=designing" class="A-t">
                  <li class="ill-1">
                      <span class="color-b <%= 'color-v' if request.original_fullpath == '/post?type=designing'%>"><i class="bi bi-palette-fill"></i></span>
                      <span class="lli-1  <%= 'color-r' if request.original_fullpath == '/post?type=designing'%>">DESIGNING</span>
                      </li>
                </a>
                <a href="/post?type=development" class="A-t">
                  <li class="ill-1">
                    <span class="color-b <%= 'color-v' if request.original_fullpath == '/post?type=development'%>"><i class="bi bi-snow2"></i></span>
                    <span class="lli-1 <%= 'color-r' if request.original_fullpath == '/post?type=development'%>">DEVELOPMENT</span>
                  </li>
                </a>
                <a href="/post?type=mobile" class="A-t">
                  <li class="ill-1">
                    <span class="color-b <%= 'color-v' if request.original_fullpath == '/post?type=mobile'%>"><i class="bi bi-phone-fill"></i></span>
                    <span class="lli-1 <%= 'color-r' if request.original_fullpath == '/post?type=mobile'%>">MOBILE</span>
                  </li>
                </a>
                <a href="/marketing" class="A-t">
                  <li class="ill-1">
                    <span class="color-b <%= 'color-v' if request.original_fullpath == '/marketing'%>"><i class="bi bi-chat-dots-fill"></i></span>
                    <span class="lli-1 <%= 'color-r' if request.original_fullpath == '/marketing'%>">MARKETING</span>
                  </li>
                </a>
                <a href="/enquiries/new" class="A-t">
                  <li class="ill-1">
                    <span class="color-b <%= 'color-v' if request.original_fullpath == '/enquiries/new'%>"><i class="bi bi-person-rolodex"></i></span>
                    <span class="lli-1 <%= 'color-r' if request.original_fullpath == '/enquiries/new'%>">CONTACT</span>
                  </li>
                </a>
                </ul>
            </div>
        </div>
    </nav>



<div class="show-1">
    <nav class="navbar navbar-expand-lg color">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">AGENCY</a>
      <button class="navbar-toggler color-1" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon "></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="/post?type=designing">Designing</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/post?type=development">Development</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/post?type=mobile">Mobile</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="/marketing">Marketing</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="/enquiries/new">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  </div>